### ISSUE TITLE
Problem with encoding 

### ISSUE THREAD

**Issue by ioverka** [enricobacis/wos#6]
```
>>> from wos import WosClient
>>> import wos.utils
>>> with WosClient() as client:
    print(wos.utils.query(client, 'UT=WOS:000330853800016'))

Authenticated (SID: ...)

Traceback (most recent call last):
  File "<pyshell#19>", line 2, in <module>
    print(wos.utils.query(client, 'UT=WOS:000330853800016'))
  File "c:\users\appdata\local\programs\git\wos\wos\utils.py", line 34, in query
    for x in range(offset, count+1, limit)]
  File "c:\users\appdata\local\programs\git\wos\wos\utils.py", line 29, in single
    return _minidom.parseString(xml).toprettyxml()
  File "C:\Python27\lib\xml\dom\minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u6768' in position 15551: ordinal not in range(128)
>>> 
```

The content-type header in the response states:
`text/xml;charset=ISO-8859-1`

... but I guess it's not:
`...<display_name>杨, 宇栋</display_name><full_name>杨, 宇栋</full_name><first_name>宇栋</first_name><last_name>杨</last_name>...`

**Comment by enricobacis** [comment]
Interesting. In 7c2b67ca9ba95b3bebc7d2df5809e0cb4a48ceb7 I encode to UTF-8 before parsing the xml, and now it is working as expected.

Thank you
